### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by chrisjcodes** [Relaxed-Theme/vscode-theme-relaxed#2]
**OS:** Mac OS High Sierra 10.13.4
**VSCode version:** 1.22.2 (1.22.2)
**Previous Theme:** Palenight Operator

**Steps to reproduce:**
- Installed theme via extensions manager
- Open command palette (cmd + shift + p)
- Preferences > Color Theme
- Highlight "Relaxed"
- Press enter

**Expected results** 
- When highlighting the theme name, I would see a preview of the theme applied to my current tab
- When pressing enter the theme would be set

**Actual results**
- No preview is shown, instead I see my current theme
- Setting the theme does nothing
- When checking the current theme after pressing enter, it is still my previous theme

**Comment by mischah** [comment]
Thanks. For the detailed information.

There was a trailing comma in the latest release. Fixed and published with 1.0.2 🙈
