### ISSUE TITLE
how to enable Dank Mono on this theme?

### ISSUE THREAD

**Issue by PovilasC** [Relaxed-Theme/vscode-theme-relaxed#7]
Hi. first of all, this is my favorite theme and I have tried many. But I ran into an issue when I try to apply Dank Mono font on this color theme. Dank Mono font works for me with other themes but not with this one. Any solution?

**Comment by mischah** [comment]
Hej @PovilasC,

where can I get the font to reproduce the issue?

Cheers, Michael

**Comment by PovilasC** [comment]
> Hej @PovilasC,
> 
> where can I get the font to reproduce the issue?
> 
> Cheers, Michael

Could you please share your email address with me, I will send it to you.

**Comment by mischah** [comment]
Me email adress is:

```
blah bleh blee. blee blaa. blah bleh bluuh. blah bleh blahh. blehh bleeh. blah bleh blee. blah bleh bluuh. blee blee. blah bleh bleeh. blee blaa. blah bleh blah. blah bleh blahh. bleeh bluuh. blah bleh blaa. blah blah blaa. blah bleh blah. blah bleh bleeh. blah blah bleh. blah bleh blah. blah bleh blahh. bleeh blehh. blah bleh bleh. blah bleh blah
```

Use [blah-code](https://bullg.it/blah-code/) to decode it 😂

**Comment by mischah** [comment]
The file has arrived. Going to investigate soonish :octocat:

**Comment by mischah** [comment]
It seems to work well. Can you specify your expectations vs. the current behavior?

<img width="997" alt="cli js ibrew 2019-03-08 18-52-49" src="https://user-images.githubusercontent.com/441011/54046060-937f2900-41d3-11e9-9b72-b5d5fff6b7c3.png">
<img width="1035" alt="settings ibrew 2019-03-08 18-51-40" src="https://user-images.githubusercontent.com/441011/54046064-95e18300-41d3-11e9-8bda-f18288a6d8e6.png">
<img width="829" alt="settings json ibrew 2019-03-08 18-51-06" src="https://user-images.githubusercontent.com/441011/54046069-98dc7380-41d3-11e9-97e8-3195413622df.png">

**Comment by mischah** [comment]
🛎 @PovilasC

**Comment by PovilasC** [comment]
> It seems to work well. Can you specify your expectations vs. the current behavior?
> 
> <img alt="cli js ibrew 2019-03-08 18-52-49" width="997" src="https://user-images.githubusercontent.com/441011/54046060-937f2900-41d3-11e9-9b72-b5d5fff6b7c3.png">
> 
> <img alt="settings ibrew 2019-03-08 18-51-40" width="1035" src="https://user-images.githubusercontent.com/441011/54046064-95e18300-41d3-11e9-8bda-f18288a6d8e6.png">
> 
> <img alt="settings json ibrew 2019-03-08 18-51-06" width="829" src="https://user-images.githubusercontent.com/441011/54046069-98dc7380-41d3-11e9-97e8-3195413622df.png">

I apologize. I wrote Dank Mono instead of DankMono-Regular 😣it works👌

**Comment by mischah** [comment]
No problem 😊 

Enjoy working with the relaxed theme.

**Comment by leiwng** [comment]
Just "Dank Mono" in Win10 for vscode setting.json

**Comment by kshitizbuilds** [comment]
which one should i use dank mono 491 or dankmono 1.000 ?? which one is better??

**Comment by lakshits11** [comment]
> Could you please share your email address with me, I will send it to you.

Hey there, can I also get the font file please 😅😅

**Comment by mischah** [comment]
> > Could you please share your email address with me, I will send it to you.
> 
> Hey there, can I also get the font file please 😅😅

Sorry, this is not a file sharing forum!

**Comment by lakshits11** [comment]
Sorry if you misunderstood me, it's just that I see this font everywhere
but I can't afford to buy it . Therefore, I was just asking for it that
maybe someone kind can share it.
